# Generated by Django 5.1 on 2024-08-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highscore',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='highscore',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
